name: Verify markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  
jobs:
  verify-links:
    runs-on: ubuntu-latest
    steps:
      - name: clone md-check-link
        run: |
          git clone https://github.com/kyma-project/md-check-link.git /tmp/md-check-link
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install 
        working-directory: /tmp/md-check-link
        run: npm install
      - uses: actions/checkout@v4
      - name: Verify links
        run: |          
          node /tmp/md-check-link/md-check-link.js -q -n 8 -c /tmp/md-check-link/.mlc.config.json ./
